baseURL = "https://blocker.neverfapdeluxe.com/"
title = "NeverFap Deluxe Blocker | Get Immediate Help With Your Porn Addiction."
languageCode = "en-us"
theme = "blocker_theme"

enableRobotsTXT = true
canonifyURLs = true
googleAnalytics = "UA-132863786-4"
